!=======================================================================
! Generated by  : PSCAD v4.5.0.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

!     SUBR    3PHVSRC       ! 3-Phase Source model

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_10(3)

! Control Signals
      INTEGER  BRK, IT_1, IT_2, IT_3, IT_4, IT_5
      INTEGER  IT_6, IT_7
      REAL     RT_1, RT_2, Vb1(3), Vf1(7)
      REAL     Vph1(7), Vph2(7), Vf2(7), Vb2(3)
      REAL     Vb3(3), Vf3(7), Vph3(7), Vb4(3)
      REAL     Vf14(7), Vph4(7), Vb5(3), Vf5(7)
      REAL     Vph5(7), Vf5_rms, Vf4_rms, P2_5
      REAL     Q2_5, P1_3, Q1_3, R, Vf3_rms
      REAL     Vf2_rms, Vf1_rms, P1_2, Q1_2, P2_3
      REAL     Q2_3, P3_4, Q3_4, P2_4, Q2_4, L
      REAL     Vph5_rms, Vph4_rms, Vph3_rms
      REAL     Vph2_rms, Vph1_rms, Q5, P5, Q4, P4
      REAL     RT_3(7), RT_4(7), RT_5, RT_6, RT_7
      REAL     RT_8(7), RT_9(7), RT_10(7)
      REAL     RT_11(7), RT_12, RT_13, RT_14
      REAL     RT_15(7), RT_16(7), RT_17(7)
      REAL     RT_18(7), RT_19, RT_20, RT_21
      REAL     RT_22(7), RT_23(7), RT_24(7)
      REAL     RT_25(7), RT_26, RT_27, RT_28
      REAL     RT_29(7), RT_30(7), RT_31(7)
      REAL     RT_32(7), RT_33, RT_34, RT_35
      REAL     RT_36(7), RT_37(7), RT_38, RT_39
      REAL     RT_40, RT_41, RT_42, RT_43, RT_44
      REAL     P1, Q1, V1, Ph1, P2, Q2, V2, Ph2
      REAL     P4_5, Q4_5, V5, Ph5, V4, Ph4, P3
      REAL     Q3, V3, Ph3

! Internal Variables
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4
      REAL     RVD1_5, RVD1_6, RVD1_7

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER ISUBS, SS(5), IBRCH(5), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 8
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 295
      NPGB      = NPGB + 26
      INODE     = NNODE + 2
      NNODE     = NNODE + 56

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 5

      DO IT_0 = 1,5
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 12

      IBRCH(2)     = NBRCH(SS(2))
      NBRCH(SS(2)) = NBRCH(SS(2)) + 15

      IBRCH(3)     = NBRCH(SS(3))
      NBRCH(SS(3)) = NBRCH(SS(3)) + 15

      IBRCH(4)     = NBRCH(SS(4))
      NBRCH(SS(4)) = NBRCH(SS(4)) + 18

      IBRCH(5)     = NBRCH(SS(5))
      NBRCH(SS(5)) = NBRCH(SS(5)) + 9
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      Vf5_rms  = STOF(ISTOF + 88)
      Vf4_rms  = STOF(ISTOF + 89)
      BRK      = STOI(ISTOI + 1)
      P2_5     = STOF(ISTOF + 90)
      Q2_5     = STOF(ISTOF + 91)
      P1_3     = STOF(ISTOF + 92)
      Q1_3     = STOF(ISTOF + 93)
      R        = STOF(ISTOF + 94)
      Vf3_rms  = STOF(ISTOF + 95)
      Vf2_rms  = STOF(ISTOF + 96)
      Vf1_rms  = STOF(ISTOF + 97)
      P1_2     = STOF(ISTOF + 98)
      Q1_2     = STOF(ISTOF + 99)
      P2_3     = STOF(ISTOF + 100)
      Q2_3     = STOF(ISTOF + 101)
      P3_4     = STOF(ISTOF + 102)
      Q3_4     = STOF(ISTOF + 103)
      P2_4     = STOF(ISTOF + 104)
      Q2_4     = STOF(ISTOF + 105)
      L        = STOF(ISTOF + 106)
      Vph5_rms = STOF(ISTOF + 107)
      Vph4_rms = STOF(ISTOF + 108)
      Vph3_rms = STOF(ISTOF + 109)
      Vph2_rms = STOF(ISTOF + 110)
      Vph1_rms = STOF(ISTOF + 111)
      Q5       = STOF(ISTOF + 112)
      P5       = STOF(ISTOF + 113)
      Q4       = STOF(ISTOF + 114)
      P4       = STOF(ISTOF + 115)
      RT_5     = STOF(ISTOF + 130)
      RT_6     = STOF(ISTOF + 131)
      RT_7     = STOF(ISTOF + 132)
      RT_12    = STOF(ISTOF + 161)
      RT_13    = STOF(ISTOF + 162)
      RT_14    = STOF(ISTOF + 163)
      RT_19    = STOF(ISTOF + 192)
      RT_20    = STOF(ISTOF + 193)
      RT_21    = STOF(ISTOF + 194)
      RT_26    = STOF(ISTOF + 223)
      RT_27    = STOF(ISTOF + 224)
      RT_28    = STOF(ISTOF + 225)
      RT_33    = STOF(ISTOF + 254)
      RT_34    = STOF(ISTOF + 255)
      RT_35    = STOF(ISTOF + 256)
      RT_38    = STOF(ISTOF + 271)
      RT_39    = STOF(ISTOF + 272)
      IT_1     = STOI(ISTOI + 2)
      RT_40    = STOF(ISTOF + 273)
      IT_2     = STOI(ISTOI + 3)
      IT_3     = STOI(ISTOI + 4)
      RT_41    = STOF(ISTOF + 274)
      RT_42    = STOF(ISTOF + 275)
      IT_4     = STOI(ISTOI + 5)
      RT_43    = STOF(ISTOF + 276)
      IT_5     = STOI(ISTOI + 6)
      RT_44    = STOF(ISTOF + 277)
      IT_6     = STOI(ISTOI + 7)
      IT_7     = STOI(ISTOI + 8)
      P1       = STOF(ISTOF + 278)
      Q1       = STOF(ISTOF + 279)
      V1       = STOF(ISTOF + 280)
      Ph1      = STOF(ISTOF + 281)
      P2       = STOF(ISTOF + 282)
      Q2       = STOF(ISTOF + 283)
      V2       = STOF(ISTOF + 284)
      Ph2      = STOF(ISTOF + 285)
      P4_5     = STOF(ISTOF + 286)
      Q4_5     = STOF(ISTOF + 287)
      V5       = STOF(ISTOF + 288)
      Ph5      = STOF(ISTOF + 289)
      V4       = STOF(ISTOF + 290)
      Ph4      = STOF(ISTOF + 291)
      P3       = STOF(ISTOF + 292)
      Q3       = STOF(ISTOF + 293)
      V3       = STOF(ISTOF + 294)
      Ph3      = STOF(ISTOF + 295)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vb1(IT_0) = STOF(ISTOF + 2 + IT_0)
         Vb2(IT_0) = STOF(ISTOF + 33 + IT_0)
         Vb3(IT_0) = STOF(ISTOF + 36 + IT_0)
         Vb4(IT_0) = STOF(ISTOF + 53 + IT_0)
         Vb5(IT_0) = STOF(ISTOF + 70 + IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         Vf1(IT_0) = STOF(ISTOF + 5 + IT_0)
         Vph1(IT_0) = STOF(ISTOF + 12 + IT_0)
         Vph2(IT_0) = STOF(ISTOF + 19 + IT_0)
         Vf2(IT_0) = STOF(ISTOF + 26 + IT_0)
         Vf3(IT_0) = STOF(ISTOF + 39 + IT_0)
         Vph3(IT_0) = STOF(ISTOF + 46 + IT_0)
         Vf14(IT_0) = STOF(ISTOF + 56 + IT_0)
         Vph4(IT_0) = STOF(ISTOF + 63 + IT_0)
         Vf5(IT_0) = STOF(ISTOF + 73 + IT_0)
         Vph5(IT_0) = STOF(ISTOF + 80 + IT_0)
         RT_3(IT_0) = STOF(ISTOF + 115 + IT_0)
         RT_4(IT_0) = STOF(ISTOF + 122 + IT_0)
         RT_8(IT_0) = STOF(ISTOF + 132 + IT_0)
         RT_9(IT_0) = STOF(ISTOF + 139 + IT_0)
         RT_10(IT_0) = STOF(ISTOF + 146 + IT_0)
         RT_11(IT_0) = STOF(ISTOF + 153 + IT_0)
         RT_15(IT_0) = STOF(ISTOF + 163 + IT_0)
         RT_16(IT_0) = STOF(ISTOF + 170 + IT_0)
         RT_17(IT_0) = STOF(ISTOF + 177 + IT_0)
         RT_18(IT_0) = STOF(ISTOF + 184 + IT_0)
         RT_22(IT_0) = STOF(ISTOF + 194 + IT_0)
         RT_23(IT_0) = STOF(ISTOF + 201 + IT_0)
         RT_24(IT_0) = STOF(ISTOF + 208 + IT_0)
         RT_25(IT_0) = STOF(ISTOF + 215 + IT_0)
         RT_29(IT_0) = STOF(ISTOF + 225 + IT_0)
         RT_30(IT_0) = STOF(ISTOF + 232 + IT_0)
         RT_31(IT_0) = STOF(ISTOF + 239 + IT_0)
         RT_32(IT_0) = STOF(ISTOF + 246 + IT_0)
         RT_36(IT_0) = STOF(ISTOF + 256 + IT_0)
         RT_37(IT_0) = STOF(ISTOF + 263 + IT_0)
      END DO

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_10(IT_0) = NODE(INODE + 30 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 30:[consti] Integer Constant 
      IT_2 = 230

! 50:[square] Square 
      RT_40 = REAL(IT_2) * REAL(IT_2)

! 90:[consti] Integer Constant 
      IT_5 = 230

! 110:[square] Square 
      RT_43 = REAL(IT_5) * REAL(IT_5)

! 140:[time-sig] Output of Simulation Time 
      RT_38 = TIME

! 160:[time-sig] Output of Simulation Time 
      RT_41 = TIME

! 180:[consti] Integer Constant 
      IT_7 = 377

! 200:[consti] Integer Constant 
      IT_3 = 1

! 210:[consti] Integer Constant 
      IT_1 = 60

! 220:[consti] Integer Constant 
      IT_6 = 10

! 230:[consti] Integer Constant 
      IT_4 = 10

! 280:[tbreakn] Timed Breaker Logic 
! Timed breaker logic
      IF ( TIMEZERO ) THEN
         BRK = 0
      ELSE
         BRK = 0
         IF ( TIME .GE. 100.0 ) BRK = (1-0)
      ENDIF

! 510:[mult] Multiplier 
      RT_39 = RT_38 * REAL(IT_3)

! 520:[mult] Multiplier 
      RT_42 = RT_41 * REAL(IT_6)

! 530:[sumjct] Summing/Differencing Junctions 
      RT_2 = + RT_42 + REAL(IT_4)

! 640:[div] Divider 
!
      IF (ABS(RT_2) .LT. 1.0E-10) THEN
         IF (RT_2 .LT. 0.0)  THEN
            RT_44 = -1.0E10 * RT_43
         ELSE
            RT_44 =  1.0E10 * RT_43
         ENDIF
      ELSE
         RT_44 = RT_43 / RT_2
      ENDIF
!

! 750:[breaker3] 3 Phase Breaker 'BRK'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(4), (IBRCH(4)+13),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(BRK)))
      CALL EMTDC_BREAKER1(SS(4), (IBRCH(4)+14),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(BRK)))
      CALL EMTDC_BREAKER1(SS(4), (IBRCH(4)+15),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(BRK)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(4)+13),SS(4)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(4)+14),SS(4)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(4)+15),SS(4)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI(1797567955,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI(1797567955,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI(1797567955,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(4)+13),SS(4)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(4)+14),SS(4)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(4)+15),SS(4)))

! 760:[sumjct] Summing/Differencing Junctions 
      RT_1 = + RT_39 + REAL(IT_1)

! 770:[div] Divider 
!
      IF (ABS(REAL(IT_7)) .LT. 1.0E-10) THEN
         IF (REAL(IT_7) .LT. 0.0)  THEN
            L = -1.0E10 * RT_44
         ELSE
            L =  1.0E10 * RT_44
         ENDIF
      ELSE
         L = RT_44 / REAL(IT_7)
      ENDIF
!

! 780:[div] Divider 
!
      IF (ABS(RT_1) .LT. 1.0E-10) THEN
         IF (RT_1 .LT. 0.0)  THEN
            R = -1.0E10 * RT_40
         ELSE
            R =  1.0E10 * RT_40
         ENDIF
      ELSE
         R = RT_40 / RT_1
      ENDIF
!

! 1:[source_3] Three Phase Voltage Source Model 2 'Source 1'
! Three Phase Source: Source 1  Type: Ideal
! With specified terminal conditions
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF  = NRTCF + 4
      CALL EMTDC_3PHVSRC(SS(1), (IBRCH(1)+1), (IBRCH(1)+2), (IBRCH(1)+3)&
     &, RVD1_4, .TRUE., RVD1_1 , RVD1_2, RVD1_3)
!

! 1:[fixed_load] Fixed Load 
      CALL LOAD3P1_EXE(SS(2), (IBRCH(2)+1), (IBRCH(2)+2), (IBRCH(2)+3), &
     &(IBRCH(2)+4), (IBRCH(2)+5), (IBRCH(2)+6))

! 1:[fixed_load] Fixed Load 
      CALL LOAD3P1_EXE(SS(3), (IBRCH(3)+10), (IBRCH(3)+11), (IBRCH(3)+12&
     &), (IBRCH(3)+13), (IBRCH(3)+14), (IBRCH(3)+15))

! 1:[fixed_load] Fixed Load 
      CALL LOAD3P1_EXE(SS(4), (IBRCH(4)+1), (IBRCH(4)+2), (IBRCH(4)+3), &
     &(IBRCH(4)+4), (IBRCH(4)+5), (IBRCH(4)+6))

! 1:[source3] Three Phase Voltage Source Model 1 'Source1'
!  3-Phase source: Source1
      RVD1_1 = RTCF(NRTCF+12)
      RVD1_2 = RTCF(NRTCF+14)
      RVD1_3 = RTCF(NRTCF+13)
      CALL ESYS651_EXE(SS(4), (IBRCH(4)+10), (IBRCH(4)+11), (IBRCH(4)+12&
     &),0,0,0, SS(4), NT_10(1),NT_10(2),NT_10(3), 0, RVD1_2, RVD1_1, 0.0&
     &5, 1.0, 1.0, 1.0,RVD1_3, 1.0, 0.05, 0.2, 0.4, 0.02, 0.5, RVD1_4, R&
     &VD1_5, RVD1_6, RVD1_7)

! 1:[fixed_load] Fixed Load 
      CALL LOAD3P1_EXE(SS(5), (IBRCH(5)+4), (IBRCH(5)+5), (IBRCH(5)+6), &
     &(IBRCH(5)+7), (IBRCH(5)+8), (IBRCH(5)+9))

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 88) = Vf5_rms
      STOF(ISTOF + 89) = Vf4_rms
      STOI(ISTOI + 1) = BRK
      STOF(ISTOF + 90) = P2_5
      STOF(ISTOF + 91) = Q2_5
      STOF(ISTOF + 92) = P1_3
      STOF(ISTOF + 93) = Q1_3
      STOF(ISTOF + 94) = R
      STOF(ISTOF + 95) = Vf3_rms
      STOF(ISTOF + 96) = Vf2_rms
      STOF(ISTOF + 97) = Vf1_rms
      STOF(ISTOF + 98) = P1_2
      STOF(ISTOF + 99) = Q1_2
      STOF(ISTOF + 100) = P2_3
      STOF(ISTOF + 101) = Q2_3
      STOF(ISTOF + 102) = P3_4
      STOF(ISTOF + 103) = Q3_4
      STOF(ISTOF + 104) = P2_4
      STOF(ISTOF + 105) = Q2_4
      STOF(ISTOF + 106) = L
      STOF(ISTOF + 107) = Vph5_rms
      STOF(ISTOF + 108) = Vph4_rms
      STOF(ISTOF + 109) = Vph3_rms
      STOF(ISTOF + 110) = Vph2_rms
      STOF(ISTOF + 111) = Vph1_rms
      STOF(ISTOF + 112) = Q5
      STOF(ISTOF + 113) = P5
      STOF(ISTOF + 114) = Q4
      STOF(ISTOF + 115) = P4
      STOF(ISTOF + 130) = RT_5
      STOF(ISTOF + 131) = RT_6
      STOF(ISTOF + 132) = RT_7
      STOF(ISTOF + 161) = RT_12
      STOF(ISTOF + 162) = RT_13
      STOF(ISTOF + 163) = RT_14
      STOF(ISTOF + 192) = RT_19
      STOF(ISTOF + 193) = RT_20
      STOF(ISTOF + 194) = RT_21
      STOF(ISTOF + 223) = RT_26
      STOF(ISTOF + 224) = RT_27
      STOF(ISTOF + 225) = RT_28
      STOF(ISTOF + 254) = RT_33
      STOF(ISTOF + 255) = RT_34
      STOF(ISTOF + 256) = RT_35
      STOF(ISTOF + 271) = RT_38
      STOF(ISTOF + 272) = RT_39
      STOI(ISTOI + 2) = IT_1
      STOF(ISTOF + 273) = RT_40
      STOI(ISTOI + 3) = IT_2
      STOI(ISTOI + 4) = IT_3
      STOF(ISTOF + 274) = RT_41
      STOF(ISTOF + 275) = RT_42
      STOI(ISTOI + 5) = IT_4
      STOF(ISTOF + 276) = RT_43
      STOI(ISTOI + 6) = IT_5
      STOF(ISTOF + 277) = RT_44
      STOI(ISTOI + 7) = IT_6
      STOI(ISTOI + 8) = IT_7
      STOF(ISTOF + 278) = P1
      STOF(ISTOF + 279) = Q1
      STOF(ISTOF + 280) = V1
      STOF(ISTOF + 281) = Ph1
      STOF(ISTOF + 282) = P2
      STOF(ISTOF + 283) = Q2
      STOF(ISTOF + 284) = V2
      STOF(ISTOF + 285) = Ph2
      STOF(ISTOF + 286) = P4_5
      STOF(ISTOF + 287) = Q4_5
      STOF(ISTOF + 288) = V5
      STOF(ISTOF + 289) = Ph5
      STOF(ISTOF + 290) = V4
      STOF(ISTOF + 291) = Ph4
      STOF(ISTOF + 292) = P3
      STOF(ISTOF + 293) = Q3
      STOF(ISTOF + 294) = V3
      STOF(ISTOF + 295) = Ph3

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 2 + IT_0) = Vb1(IT_0)
         STOF(ISTOF + 33 + IT_0) = Vb2(IT_0)
         STOF(ISTOF + 36 + IT_0) = Vb3(IT_0)
         STOF(ISTOF + 53 + IT_0) = Vb4(IT_0)
         STOF(ISTOF + 70 + IT_0) = Vb5(IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         STOF(ISTOF + 5 + IT_0) = Vf1(IT_0)
         STOF(ISTOF + 12 + IT_0) = Vph1(IT_0)
         STOF(ISTOF + 19 + IT_0) = Vph2(IT_0)
         STOF(ISTOF + 26 + IT_0) = Vf2(IT_0)
         STOF(ISTOF + 39 + IT_0) = Vf3(IT_0)
         STOF(ISTOF + 46 + IT_0) = Vph3(IT_0)
         STOF(ISTOF + 56 + IT_0) = Vf14(IT_0)
         STOF(ISTOF + 63 + IT_0) = Vph4(IT_0)
         STOF(ISTOF + 73 + IT_0) = Vf5(IT_0)
         STOF(ISTOF + 80 + IT_0) = Vph5(IT_0)
         STOF(ISTOF + 115 + IT_0) = RT_3(IT_0)
         STOF(ISTOF + 122 + IT_0) = RT_4(IT_0)
         STOF(ISTOF + 132 + IT_0) = RT_8(IT_0)
         STOF(ISTOF + 139 + IT_0) = RT_9(IT_0)
         STOF(ISTOF + 146 + IT_0) = RT_10(IT_0)
         STOF(ISTOF + 153 + IT_0) = RT_11(IT_0)
         STOF(ISTOF + 163 + IT_0) = RT_15(IT_0)
         STOF(ISTOF + 170 + IT_0) = RT_16(IT_0)
         STOF(ISTOF + 177 + IT_0) = RT_17(IT_0)
         STOF(ISTOF + 184 + IT_0) = RT_18(IT_0)
         STOF(ISTOF + 194 + IT_0) = RT_22(IT_0)
         STOF(ISTOF + 201 + IT_0) = RT_23(IT_0)
         STOF(ISTOF + 208 + IT_0) = RT_24(IT_0)
         STOF(ISTOF + 215 + IT_0) = RT_25(IT_0)
         STOF(ISTOF + 225 + IT_0) = RT_29(IT_0)
         STOF(ISTOF + 232 + IT_0) = RT_30(IT_0)
         STOF(ISTOF + 239 + IT_0) = RT_31(IT_0)
         STOF(ISTOF + 246 + IT_0) = RT_32(IT_0)
         STOF(ISTOF + 256 + IT_0) = RT_36(IT_0)
         STOF(ISTOF + 263 + IT_0) = RT_37(IT_0)
      END DO

!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    P3PH3         ! 
      REAL    Q3PH3         ! 
      REAL    VM3PH2        ! '3 Phase RMS Voltage Measurement'
      REAL    EMTDC_VVDC    ! 
!     SUBR    MPHASE3PS     ! Phase Measurement in a 3p signal
!     SUBR    FTN180        ! FFT Calculation
      REAL    VBRANCH       ! 

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_8(3), Bus2(3), NT_10(3)
      INTEGER  Bus1(3), Bus5(3), Bus4(3), Bus3(3)

! Control Signals
      REAL     Vb1(3), Vf1(7), Vph1(7), Vph2(7)
      REAL     Vf2(7), Vb2(3), Vb3(3), Vf3(7)
      REAL     Vph3(7), Vb4(3), Vf14(7), Vph4(7)
      REAL     Vb5(3), Vf5(7), Vph5(7), Vf5_rms
      REAL     Vf4_rms, P2_5, Q2_5, P1_3, Q1_3
      REAL     Vf3_rms, Vf2_rms, Vf1_rms, P1_2
      REAL     Q1_2, P2_3, Q2_3, P3_4, Q3_4, P2_4
      REAL     Q2_4, Vph5_rms, Vph4_rms, Vph3_rms
      REAL     Vph2_rms, Vph1_rms, Q5, P5, Q4, P4
      REAL     RT_3(7), RT_4(7), RT_5, RT_6, RT_7
      REAL     RT_8(7), RT_9(7), RT_10(7)
      REAL     RT_11(7), RT_12, RT_13, RT_14
      REAL     RT_15(7), RT_16(7), RT_17(7)
      REAL     RT_18(7), RT_19, RT_20, RT_21
      REAL     RT_22(7), RT_23(7), RT_24(7)
      REAL     RT_25(7), RT_26, RT_27, RT_28
      REAL     RT_29(7), RT_30(7), RT_31(7)
      REAL     RT_32(7), RT_33, RT_34, RT_35
      REAL     RT_36(7), RT_37(7), P1, Q1, V1
      REAL     Ph1, P2, Q2, V2, Ph2, P4_5, Q4_5
      REAL     V5, Ph5, V4, Ph4, P3, Q3, V3, Ph3

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(5), IBRCH(5), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 26
      INODE     = NNODE + 2
      NNODE     = NNODE + 56

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 5

      DO IT_0 = 1,5
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 12

      IBRCH(2)     = NBRCH(SS(2))
      NBRCH(SS(2)) = NBRCH(SS(2)) + 15

      IBRCH(3)     = NBRCH(SS(3))
      NBRCH(SS(3)) = NBRCH(SS(3)) + 15

      IBRCH(4)     = NBRCH(SS(4))
      NBRCH(SS(4)) = NBRCH(SS(4)) + 18

      IBRCH(5)     = NBRCH(SS(5))
      NBRCH(SS(5)) = NBRCH(SS(5)) + 9
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      Vf5_rms  = STOF(ISTOF + 88)
      Vf4_rms  = STOF(ISTOF + 89)
      P2_5     = STOF(ISTOF + 90)
      Q2_5     = STOF(ISTOF + 91)
      P1_3     = STOF(ISTOF + 92)
      Q1_3     = STOF(ISTOF + 93)
      Vf3_rms  = STOF(ISTOF + 95)
      Vf2_rms  = STOF(ISTOF + 96)
      Vf1_rms  = STOF(ISTOF + 97)
      P1_2     = STOF(ISTOF + 98)
      Q1_2     = STOF(ISTOF + 99)
      P2_3     = STOF(ISTOF + 100)
      Q2_3     = STOF(ISTOF + 101)
      P3_4     = STOF(ISTOF + 102)
      Q3_4     = STOF(ISTOF + 103)
      P2_4     = STOF(ISTOF + 104)
      Q2_4     = STOF(ISTOF + 105)
      Vph5_rms = STOF(ISTOF + 107)
      Vph4_rms = STOF(ISTOF + 108)
      Vph3_rms = STOF(ISTOF + 109)
      Vph2_rms = STOF(ISTOF + 110)
      Vph1_rms = STOF(ISTOF + 111)
      Q5       = STOF(ISTOF + 112)
      P5       = STOF(ISTOF + 113)
      Q4       = STOF(ISTOF + 114)
      P4       = STOF(ISTOF + 115)
      RT_5     = STOF(ISTOF + 130)
      RT_6     = STOF(ISTOF + 131)
      RT_7     = STOF(ISTOF + 132)
      RT_12    = STOF(ISTOF + 161)
      RT_13    = STOF(ISTOF + 162)
      RT_14    = STOF(ISTOF + 163)
      RT_19    = STOF(ISTOF + 192)
      RT_20    = STOF(ISTOF + 193)
      RT_21    = STOF(ISTOF + 194)
      RT_26    = STOF(ISTOF + 223)
      RT_27    = STOF(ISTOF + 224)
      RT_28    = STOF(ISTOF + 225)
      RT_33    = STOF(ISTOF + 254)
      RT_34    = STOF(ISTOF + 255)
      RT_35    = STOF(ISTOF + 256)
      P1       = STOF(ISTOF + 278)
      Q1       = STOF(ISTOF + 279)
      V1       = STOF(ISTOF + 280)
      Ph1      = STOF(ISTOF + 281)
      P2       = STOF(ISTOF + 282)
      Q2       = STOF(ISTOF + 283)
      V2       = STOF(ISTOF + 284)
      Ph2      = STOF(ISTOF + 285)
      P4_5     = STOF(ISTOF + 286)
      Q4_5     = STOF(ISTOF + 287)
      V5       = STOF(ISTOF + 288)
      Ph5      = STOF(ISTOF + 289)
      V4       = STOF(ISTOF + 290)
      Ph4      = STOF(ISTOF + 291)
      P3       = STOF(ISTOF + 292)
      Q3       = STOF(ISTOF + 293)
      V3       = STOF(ISTOF + 294)
      Ph3      = STOF(ISTOF + 295)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vb1(IT_0) = STOF(ISTOF + 2 + IT_0)
         Vb2(IT_0) = STOF(ISTOF + 33 + IT_0)
         Vb3(IT_0) = STOF(ISTOF + 36 + IT_0)
         Vb4(IT_0) = STOF(ISTOF + 53 + IT_0)
         Vb5(IT_0) = STOF(ISTOF + 70 + IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         Vf1(IT_0) = STOF(ISTOF + 5 + IT_0)
         Vph1(IT_0) = STOF(ISTOF + 12 + IT_0)
         Vph2(IT_0) = STOF(ISTOF + 19 + IT_0)
         Vf2(IT_0) = STOF(ISTOF + 26 + IT_0)
         Vf3(IT_0) = STOF(ISTOF + 39 + IT_0)
         Vph3(IT_0) = STOF(ISTOF + 46 + IT_0)
         Vf14(IT_0) = STOF(ISTOF + 56 + IT_0)
         Vph4(IT_0) = STOF(ISTOF + 63 + IT_0)
         Vf5(IT_0) = STOF(ISTOF + 73 + IT_0)
         Vph5(IT_0) = STOF(ISTOF + 80 + IT_0)
         RT_3(IT_0) = STOF(ISTOF + 115 + IT_0)
         RT_4(IT_0) = STOF(ISTOF + 122 + IT_0)
         RT_8(IT_0) = STOF(ISTOF + 132 + IT_0)
         RT_9(IT_0) = STOF(ISTOF + 139 + IT_0)
         RT_10(IT_0) = STOF(ISTOF + 146 + IT_0)
         RT_11(IT_0) = STOF(ISTOF + 153 + IT_0)
         RT_15(IT_0) = STOF(ISTOF + 163 + IT_0)
         RT_16(IT_0) = STOF(ISTOF + 170 + IT_0)
         RT_17(IT_0) = STOF(ISTOF + 177 + IT_0)
         RT_18(IT_0) = STOF(ISTOF + 184 + IT_0)
         RT_22(IT_0) = STOF(ISTOF + 194 + IT_0)
         RT_23(IT_0) = STOF(ISTOF + 201 + IT_0)
         RT_24(IT_0) = STOF(ISTOF + 208 + IT_0)
         RT_25(IT_0) = STOF(ISTOF + 215 + IT_0)
         RT_29(IT_0) = STOF(ISTOF + 225 + IT_0)
         RT_30(IT_0) = STOF(ISTOF + 232 + IT_0)
         RT_31(IT_0) = STOF(ISTOF + 239 + IT_0)
         RT_32(IT_0) = STOF(ISTOF + 246 + IT_0)
         RT_36(IT_0) = STOF(ISTOF + 256 + IT_0)
         RT_37(IT_0) = STOF(ISTOF + 263 + IT_0)
      END DO

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_8(IT_0) = NODE(INODE + 21 + IT_0)
         Bus2(IT_0) = NODE(INODE + 24 + IT_0)
         NT_10(IT_0) = NODE(INODE + 30 + IT_0)
         Bus1(IT_0) = NODE(INODE + 33 + IT_0)
         Bus5(IT_0) = NODE(INODE + 36 + IT_0)
         Bus4(IT_0) = NODE(INODE + 42 + IT_0)
         Bus3(IT_0) = NODE(INODE + 48 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(1), (IBRCH(1)+7), (IBRCH(1)+8), (&
     &IBRCH(1)+9),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(1378704669,RVD1_1,"Pd")
      P1 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(1), (IBRCH(1)+7), (IBRCH(1)+8), (&
     &IBRCH(1)+9),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(1378704669,RVD1_1,"Qd")
      Q1 = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS(1), NT_8(1), NT_8(2), NT_8(3),&
     & RTCF(IVD1_1+2))
      IF (UPDATE_AG) CALL PSCAD_AGRG(1378704669,RVD1_1,"Vd")
      V1 = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS(1), NT_8(1), 0)
      RVD1_3 = EMTDC_VVDC(SS(1), NT_8(2), 0)
      RVD1_4 = EMTDC_VVDC(SS(1), NT_8(3), 0)
      CALL MPHASE3PS(0, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      Ph1 = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(1378704669,1,"hide1")
        CALL PSCAD_AGI(1378704669,1,"hide2")
      ENDIF

! 20:[voltmetergnd] Voltmeter (Line - Ground) 'Vb1'
      Vb1(1) = EMTDC_VVDC(SS(1), Bus1(1), 0)
      Vb1(2) = EMTDC_VVDC(SS(1), Bus1(2), 0)
      Vb1(3) = EMTDC_VVDC(SS(1), Bus1(3), 0)

! 40:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(2), (IBRCH(2)+13), (IBRCH(2)+14),&
     & (IBRCH(2)+15),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(587221812,RVD1_1,"Pd")
      P3 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(2), (IBRCH(2)+13), (IBRCH(2)+14),&
     & (IBRCH(2)+15),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(587221812,RVD1_1,"Qd")
      Q3 = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS(2), Bus3(1), Bus3(2), Bus3(3),&
     & RTCF(IVD1_1+2))
      IF (UPDATE_AG) CALL PSCAD_AGRG(587221812,RVD1_1,"Vd")
      V3 = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS(2), Bus3(1), 0)
      RVD1_3 = EMTDC_VVDC(SS(2), Bus3(2), 0)
      RVD1_4 = EMTDC_VVDC(SS(2), Bus3(3), 0)
      CALL MPHASE3PS(0, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      Ph3 = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(587221812,1,"hide1")
        CALL PSCAD_AGI(587221812,1,"hide2")
      ENDIF

! 60:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(3), (IBRCH(3)+7), (IBRCH(3)+8), (&
     &IBRCH(3)+9),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(384787598,RVD1_1,"Pd")
      P4 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(3), (IBRCH(3)+7), (IBRCH(3)+8), (&
     &IBRCH(3)+9),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(384787598,RVD1_1,"Qd")
      Q4 = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS(3), Bus4(1), Bus4(2), Bus4(3),&
     & RTCF(IVD1_1+2))
      IF (UPDATE_AG) CALL PSCAD_AGRG(384787598,RVD1_1,"Vd")
      V4 = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS(3), Bus4(1), 0)
      RVD1_3 = EMTDC_VVDC(SS(3), Bus4(2), 0)
      RVD1_4 = EMTDC_VVDC(SS(3), Bus4(3), 0)
      CALL MPHASE3PS(0, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      Ph4 = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(384787598,1,"hide1")
        CALL PSCAD_AGI(384787598,1,"hide2")
      ENDIF

! 70:[voltmetergnd] Voltmeter (Line - Ground) 'vb3'
      vb3(1) = EMTDC_VVDC(SS(2), Bus3(1), 0)
      vb3(2) = EMTDC_VVDC(SS(2), Bus3(2), 0)
      vb3(3) = EMTDC_VVDC(SS(2), Bus3(3), 0)

! 80:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(1), (IBRCH(1)+4), (IBRCH(1)+5), (&
     &IBRCH(1)+6),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(1693078603,RVD1_1,"Pd")
      P1_3 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(1), (IBRCH(1)+4), (IBRCH(1)+5), (&
     &IBRCH(1)+6),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(1693078603,RVD1_1,"Qd")
      Q1_3 = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS(1), Bus1(1), 0)
      RVD1_3 = EMTDC_VVDC(SS(1), Bus1(2), 0)
      RVD1_4 = EMTDC_VVDC(SS(1), Bus1(3), 0)
      CALL MPHASE3PS(0, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(1693078603,1,"hide1")
        CALL PSCAD_AGI(1693078603,1,"hide2")
      ENDIF

! 100:[voltmetergnd] Voltmeter (Line - Ground) 'Vb4'
      Vb4(1) = EMTDC_VVDC(SS(3), Bus4(1), 0)
      Vb4(2) = EMTDC_VVDC(SS(3), Bus4(2), 0)
      Vb4(3) = EMTDC_VVDC(SS(3), Bus4(3), 0)

! 120:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(1), (IBRCH(1)+10), (IBRCH(1)+11),&
     & (IBRCH(1)+12),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(2005992875,RVD1_1,"Pd")
      P1_2 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(1), (IBRCH(1)+10), (IBRCH(1)+11),&
     & (IBRCH(1)+12),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(2005992875,RVD1_1,"Qd")
      Q1_2 = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(2005992875,1,"hide1")
        CALL PSCAD_AGI(2005992875,1,"hide2")
      ENDIF

! 130:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(2), (IBRCH(2)+10), (IBRCH(2)+11),&
     & (IBRCH(2)+12),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(989472091,RVD1_1,"Pd")
      P3_4 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(2), (IBRCH(2)+10), (IBRCH(2)+11),&
     & (IBRCH(2)+12),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(989472091,RVD1_1,"Qd")
      Q3_4 = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(989472091,1,"hide1")
        CALL PSCAD_AGI(989472091,1,"hide2")
      ENDIF

! 150:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(2), (IBRCH(2)+7), (IBRCH(2)+8), (&
     &IBRCH(2)+9),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(749785535,RVD1_1,"Pd")
      P2_3 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(2), (IBRCH(2)+7), (IBRCH(2)+8), (&
     &IBRCH(2)+9),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(749785535,RVD1_1,"Qd")
      Q2_3 = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(749785535,1,"hide1")
        CALL PSCAD_AGI(749785535,1,"hide2")
      ENDIF

! 170:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(3), (IBRCH(3)+4), (IBRCH(3)+5), (&
     &IBRCH(3)+6),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(1382418949,RVD1_1,"Pd")
      P4_5 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(3), (IBRCH(3)+4), (IBRCH(3)+5), (&
     &IBRCH(3)+6),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(1382418949,RVD1_1,"Qd")
      Q4_5 = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS(3), Bus4(1), 0)
      RVD1_3 = EMTDC_VVDC(SS(3), Bus4(2), 0)
      RVD1_4 = EMTDC_VVDC(SS(3), Bus4(3), 0)
      CALL MPHASE3PS(0, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(1382418949,1,"hide1")
        CALL PSCAD_AGI(1382418949,1,"hide2")
      ENDIF

! 190:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(3), (IBRCH(3)+1), (IBRCH(3)+2), (&
     &IBRCH(3)+3),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(2135884311,RVD1_1,"Pd")
      P2_4 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(3), (IBRCH(3)+1), (IBRCH(3)+2), (&
     &IBRCH(3)+3),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(2135884311,RVD1_1,"Qd")
      Q2_4 = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(2135884311,1,"hide1")
        CALL PSCAD_AGI(2135884311,1,"hide2")
      ENDIF

! 240:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(4), (IBRCH(4)+16), (IBRCH(4)+17),&
     & (IBRCH(4)+18),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(1554035066,RVD1_1,"Pd")
      P2_5 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(4), (IBRCH(4)+16), (IBRCH(4)+17),&
     & (IBRCH(4)+18),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(1554035066,RVD1_1,"Qd")
      Q2_5 = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(1554035066,1,"hide1")
        CALL PSCAD_AGI(1554035066,1,"hide2")
      ENDIF

! 250:[voltmetergnd] Voltmeter (Line - Ground) 'Vb2'
      Vb2(1) = EMTDC_VVDC(SS(4), Bus2(1), 0)
      Vb2(2) = EMTDC_VVDC(SS(4), Bus2(2), 0)
      Vb2(3) = EMTDC_VVDC(SS(4), Bus2(3), 0)

! 260:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(4), (IBRCH(4)+7), (IBRCH(4)+8), (&
     &IBRCH(4)+9),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(1160773924,RVD1_1,"Pd")
      P2 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(4), (IBRCH(4)+7), (IBRCH(4)+8), (&
     &IBRCH(4)+9),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(1160773924,RVD1_1,"Qd")
      Q2 = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS(4), NT_10(1), NT_10(2), NT_10(&
     &3), RTCF(IVD1_1+2))
      IF (UPDATE_AG) CALL PSCAD_AGRG(1160773924,RVD1_1,"Vd")
      V2 = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS(4), NT_10(1), 0)
      RVD1_3 = EMTDC_VVDC(SS(4), NT_10(2), 0)
      RVD1_4 = EMTDC_VVDC(SS(4), NT_10(3), 0)
      CALL MPHASE3PS(0, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      Ph2 = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(1160773924,1,"hide1")
        CALL PSCAD_AGI(1160773924,1,"hide2")
      ENDIF

! 270:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL FTN180(0,0,7,1,60.0,60.0,Vb1(1),IVD1_1,Vf1,Vph1,RT_5)
      CALL FTN180(0,0,7,1,60.0,60.0,Vb1(2),IVD1_1,RT_8,RT_3,RT_7)
      CALL FTN180(0,0,7,1,60.0,60.0,Vb1(3),IVD1_1,RT_9,RT_4,RT_6)
!

! 290:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL FTN180(0,0,7,1,60.0,60.0,Vb2(1),IVD1_1,Vf2,Vph2,RT_12)
      CALL FTN180(0,0,7,1,60.0,60.0,Vb2(2),IVD1_1,RT_15,RT_10,RT_14)
      CALL FTN180(0,0,7,1,60.0,60.0,Vb2(3),IVD1_1,RT_16,RT_11,RT_13)
!

! 300:[voltmetergnd] Voltmeter (Line - Ground) 'Vb5'
      Vb5(1) = EMTDC_VVDC(SS(5), Bus5(1), 0)
      Vb5(2) = EMTDC_VVDC(SS(5), Bus5(2), 0)
      Vb5(3) = EMTDC_VVDC(SS(5), Bus5(3), 0)

! 310:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL FTN180(0,0,7,1,60.0,60.0,Vb3(1),IVD1_1,Vf3,Vph3,RT_19)
      CALL FTN180(0,0,7,1,60.0,60.0,Vb3(2),IVD1_1,RT_22,RT_17,RT_21)
      CALL FTN180(0,0,7,1,60.0,60.0,Vb3(3),IVD1_1,RT_23,RT_18,RT_20)
!

! 320:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL FTN180(0,0,7,1,60.0,60.0,Vb4(1),IVD1_1,Vf14,Vph4,RT_26)
      CALL FTN180(0,0,7,1,60.0,60.0,Vb4(2),IVD1_1,RT_29,RT_24,RT_28)
      CALL FTN180(0,0,7,1,60.0,60.0,Vb4(3),IVD1_1,RT_30,RT_25,RT_27)
!

! 330:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(5), (IBRCH(5)+1), (IBRCH(5)+2), (&
     &IBRCH(5)+3),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(972352034,RVD1_1,"Pd")
      P5 = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(5), (IBRCH(5)+1), (IBRCH(5)+2), (&
     &IBRCH(5)+3),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGRG(972352034,RVD1_1,"Qd")
      Q5 = RVD1_1
      RVD1_1 = RTCF(IVD1_1+1) * VM3PH2(SS(5), Bus5(1), Bus5(2), Bus5(3),&
     & RTCF(IVD1_1+2))
      IF (UPDATE_AG) CALL PSCAD_AGRG(972352034,RVD1_1,"Vd")
      V5 = RVD1_1
      RVD1_2 = EMTDC_VVDC(SS(5), Bus5(1), 0)
      RVD1_3 = EMTDC_VVDC(SS(5), Bus5(2), 0)
      RVD1_4 = EMTDC_VVDC(SS(5), Bus5(3), 0)
      CALL MPHASE3PS(0, 1, RVD1_2, RVD1_3, RVD1_4, RTCF(IVD1_1+2), RTCF(&
     &IVD1_1+3) , RVD1_1)
      Ph5 = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI(972352034,1,"hide1")
        CALL PSCAD_AGI(972352034,1,"hide2")
      ENDIF

! 340:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL FTN180(0,0,7,1,60.0,60.0,Vb5(1),IVD1_1,Vf5,Vph5,RT_33)
      CALL FTN180(0,0,7,1,60.0,60.0,Vb5(2),IVD1_1,RT_36,RT_31,RT_35)
      CALL FTN180(0,0,7,1,60.0,60.0,Vb5(3),IVD1_1,RT_37,RT_32,RT_34)
!

! 350:[pgb] Output Channel 'P2_5'

      PGB(IPGB+1) = P2_5

! 360:[pgb] Output Channel 'P1_2'

      PGB(IPGB+2) = P1_2

! 370:[pgb] Output Channel 'P3_4'

      PGB(IPGB+3) = P3_4

! 380:[pgb] Output Channel 'Q2_5'

      PGB(IPGB+4) = Q2_5

! 390:[pgb] Output Channel 'Q1_2'

      PGB(IPGB+5) = Q1_2

! 400:[pgb] Output Channel 'Q3_4'

      PGB(IPGB+6) = Q3_4

! 410:[pgb] Output Channel 'P1_3'

      PGB(IPGB+7) = P1_3

! 420:[pgb] Output Channel 'P2_3'

      PGB(IPGB+8) = P2_3

! 430:[pgb] Output Channel 'P2_4'

      PGB(IPGB+9) = P2_4

! 440:[pgb] Output Channel 'Q1_3'

      PGB(IPGB+10) = Q1_3

! 450:[pgb] Output Channel 'Q2_3'

      PGB(IPGB+11) = Q2_3

! 460:[pgb] Output Channel 'Q2_4'

      PGB(IPGB+12) = Q2_4

! 470:[pgb] Output Channel 'P4'

      PGB(IPGB+13) = P4

! 480:[pgb] Output Channel 'Q4'

      PGB(IPGB+14) = Q4

! 490:[pgb] Output Channel 'P5'

      PGB(IPGB+15) = P5

! 500:[pgb] Output Channel 'Q5'

      PGB(IPGB+16) = Q5

! 540:[datatap] Scalar/Array Tap 
       Vf1_rms = Vf1(1)

! 550:[datatap] Scalar/Array Tap 
       Vf2_rms = Vf2(1)

! 560:[datatap] Scalar/Array Tap 
       Vf3_rms = Vf3(1)

! 570:[datatap] Scalar/Array Tap 
       Vf4_rms = Vf14(1)

! 580:[datatap] Scalar/Array Tap 
       Vf5_rms = Vf5(1)

! 590:[datatap] Scalar/Array Tap 
       Vph1_rms = Vph1(1)

! 600:[datatap] Scalar/Array Tap 
       Vph2_rms = Vph2(1)

! 610:[datatap] Scalar/Array Tap 
       Vph3_rms = Vph3(1)

! 620:[datatap] Scalar/Array Tap 
       Vph4_rms = Vph4(1)

! 630:[datatap] Scalar/Array Tap 
       Vph5_rms = Vph5(1)

! 650:[pgb] Output Channel 'Vph5_rms'

      PGB(IPGB+17) = Vph5_rms

! 660:[pgb] Output Channel 'Vf5_rms'

      PGB(IPGB+18) = Vf5_rms

! 670:[pgb] Output Channel 'Vph4_rms'

      PGB(IPGB+19) = Vph4_rms

! 680:[pgb] Output Channel 'Vf4_rms'

      PGB(IPGB+20) = Vf4_rms

! 690:[pgb] Output Channel 'Vph3_rms'

      PGB(IPGB+21) = Vph3_rms

! 700:[pgb] Output Channel 'Vf3_rms'

      PGB(IPGB+22) = Vf3_rms

! 710:[pgb] Output Channel 'Vph2_rms'

      PGB(IPGB+23) = Vph2_rms

! 720:[pgb] Output Channel 'Vf2_rms'

      PGB(IPGB+24) = Vf2_rms

! 730:[pgb] Output Channel 'Vph1_rms'

      PGB(IPGB+25) = Vph1_rms

! 740:[pgb] Output Channel 'Vf1_rms'

      PGB(IPGB+26) = Vf1_rms

! 750:[breaker3] 3 Phase Breaker 'BRK'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(4), (IBRCH(4)+13), (IBRCH(4)+14), (IBRCH(4)+15),&
     &0,0,0,IVD1_1,0.02,RVD1_1,RVD1_2)

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 88) = Vf5_rms
      STOF(ISTOF + 89) = Vf4_rms
      STOF(ISTOF + 90) = P2_5
      STOF(ISTOF + 91) = Q2_5
      STOF(ISTOF + 92) = P1_3
      STOF(ISTOF + 93) = Q1_3
      STOF(ISTOF + 95) = Vf3_rms
      STOF(ISTOF + 96) = Vf2_rms
      STOF(ISTOF + 97) = Vf1_rms
      STOF(ISTOF + 98) = P1_2
      STOF(ISTOF + 99) = Q1_2
      STOF(ISTOF + 100) = P2_3
      STOF(ISTOF + 101) = Q2_3
      STOF(ISTOF + 102) = P3_4
      STOF(ISTOF + 103) = Q3_4
      STOF(ISTOF + 104) = P2_4
      STOF(ISTOF + 105) = Q2_4
      STOF(ISTOF + 107) = Vph5_rms
      STOF(ISTOF + 108) = Vph4_rms
      STOF(ISTOF + 109) = Vph3_rms
      STOF(ISTOF + 110) = Vph2_rms
      STOF(ISTOF + 111) = Vph1_rms
      STOF(ISTOF + 112) = Q5
      STOF(ISTOF + 113) = P5
      STOF(ISTOF + 114) = Q4
      STOF(ISTOF + 115) = P4
      STOF(ISTOF + 130) = RT_5
      STOF(ISTOF + 131) = RT_6
      STOF(ISTOF + 132) = RT_7
      STOF(ISTOF + 161) = RT_12
      STOF(ISTOF + 162) = RT_13
      STOF(ISTOF + 163) = RT_14
      STOF(ISTOF + 192) = RT_19
      STOF(ISTOF + 193) = RT_20
      STOF(ISTOF + 194) = RT_21
      STOF(ISTOF + 223) = RT_26
      STOF(ISTOF + 224) = RT_27
      STOF(ISTOF + 225) = RT_28
      STOF(ISTOF + 254) = RT_33
      STOF(ISTOF + 255) = RT_34
      STOF(ISTOF + 256) = RT_35
      STOF(ISTOF + 278) = P1
      STOF(ISTOF + 279) = Q1
      STOF(ISTOF + 280) = V1
      STOF(ISTOF + 281) = Ph1
      STOF(ISTOF + 282) = P2
      STOF(ISTOF + 283) = Q2
      STOF(ISTOF + 284) = V2
      STOF(ISTOF + 285) = Ph2
      STOF(ISTOF + 286) = P4_5
      STOF(ISTOF + 287) = Q4_5
      STOF(ISTOF + 288) = V5
      STOF(ISTOF + 289) = Ph5
      STOF(ISTOF + 290) = V4
      STOF(ISTOF + 291) = Ph4
      STOF(ISTOF + 292) = P3
      STOF(ISTOF + 293) = Q3
      STOF(ISTOF + 294) = V3
      STOF(ISTOF + 295) = Ph3

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 2 + IT_0) = Vb1(IT_0)
         STOF(ISTOF + 33 + IT_0) = Vb2(IT_0)
         STOF(ISTOF + 36 + IT_0) = Vb3(IT_0)
         STOF(ISTOF + 53 + IT_0) = Vb4(IT_0)
         STOF(ISTOF + 70 + IT_0) = Vb5(IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         STOF(ISTOF + 5 + IT_0) = Vf1(IT_0)
         STOF(ISTOF + 12 + IT_0) = Vph1(IT_0)
         STOF(ISTOF + 19 + IT_0) = Vph2(IT_0)
         STOF(ISTOF + 26 + IT_0) = Vf2(IT_0)
         STOF(ISTOF + 39 + IT_0) = Vf3(IT_0)
         STOF(ISTOF + 46 + IT_0) = Vph3(IT_0)
         STOF(ISTOF + 56 + IT_0) = Vf14(IT_0)
         STOF(ISTOF + 63 + IT_0) = Vph4(IT_0)
         STOF(ISTOF + 73 + IT_0) = Vf5(IT_0)
         STOF(ISTOF + 80 + IT_0) = Vph5(IT_0)
         STOF(ISTOF + 115 + IT_0) = RT_3(IT_0)
         STOF(ISTOF + 122 + IT_0) = RT_4(IT_0)
         STOF(ISTOF + 132 + IT_0) = RT_8(IT_0)
         STOF(ISTOF + 139 + IT_0) = RT_9(IT_0)
         STOF(ISTOF + 146 + IT_0) = RT_10(IT_0)
         STOF(ISTOF + 153 + IT_0) = RT_11(IT_0)
         STOF(ISTOF + 163 + IT_0) = RT_15(IT_0)
         STOF(ISTOF + 170 + IT_0) = RT_16(IT_0)
         STOF(ISTOF + 177 + IT_0) = RT_17(IT_0)
         STOF(ISTOF + 184 + IT_0) = RT_18(IT_0)
         STOF(ISTOF + 194 + IT_0) = RT_22(IT_0)
         STOF(ISTOF + 201 + IT_0) = RT_23(IT_0)
         STOF(ISTOF + 208 + IT_0) = RT_24(IT_0)
         STOF(ISTOF + 215 + IT_0) = RT_25(IT_0)
         STOF(ISTOF + 225 + IT_0) = RT_29(IT_0)
         STOF(ISTOF + 232 + IT_0) = RT_30(IT_0)
         STOF(ISTOF + 239 + IT_0) = RT_31(IT_0)
         STOF(ISTOF + 246 + IT_0) = RT_32(IT_0)
         STOF(ISTOF + 256 + IT_0) = RT_36(IT_0)
         STOF(ISTOF + 263 + IT_0) = RT_37(IT_0)
      END DO

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_10(3)

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4, IT_5, IT_6
      INTEGER  IT_7

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(5), IBRCH(5), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 56

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 5

      DO IT_0 = 1,5
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 12

      IBRCH(2)     = NBRCH(SS(2))
      NBRCH(SS(2)) = NBRCH(SS(2)) + 15

      IBRCH(3)     = NBRCH(SS(3))
      NBRCH(SS(3)) = NBRCH(SS(3)) + 15

      IBRCH(4)     = NBRCH(SS(4))
      NBRCH(SS(4)) = NBRCH(SS(4)) + 18

      IBRCH(5)     = NBRCH(SS(5))
      NBRCH(SS(5)) = NBRCH(SS(5)) + 9
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_10(IT_0) = NODE(INODE + 30 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 30:[consti] Integer Constant 

! 50:[square] Square 

! 90:[consti] Integer Constant 

! 110:[square] Square 

! 140:[time-sig] Output of Simulation Time 

! 160:[time-sig] Output of Simulation Time 

! 180:[consti] Integer Constant 

! 200:[consti] Integer Constant 

! 210:[consti] Integer Constant 

! 220:[consti] Integer Constant 

! 230:[consti] Integer Constant 

! 510:[mult] Multiplier 

! 520:[mult] Multiplier 

! 530:[sumjct] Summing/Differencing Junctions 

! 640:[div] Divider 

! 750:[breaker3] 3 Phase Breaker 'BRK'
      CALL COMPONENT_ID(ICALL_NO,1797567955)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 760:[sumjct] Summing/Differencing Junctions 

! 770:[div] Divider 

! 780:[div] Divider 

! 1:[source_3] Three Phase Voltage Source Model 2 'Source 1'
      CALL E_3PVSRC_CFG(6,1.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,230.0,100.0,0&
     &.05)

! 1:[fixed_load] Fixed Load 
      CALL LOAD1P1_CFG(132.790562,60.0,45.0,15.0,2.0,2.0,0.0,0.0)

! 1:[fixed_load] Fixed Load 
      CALL LOAD1P1_CFG(132.790562,60.0,40.0,5.0,2.0,2.0,0.0,0.0)

! 1:[fixed_load] Fixed Load 
      CALL LOAD1P1_CFG(132.790562,60.0,20.0,10.0,2.0,2.0,0.0,0.0)

! 1:[source3] Three Phase Voltage Source Model 1 'Source1'
      CALL COMPONENT_ID(ICALL_NO,520514898)
      CALL ESYS651_CFG(3,4,1,0,1,SS(4), (IBRCH(4)+10), (IBRCH(4)+11), (I&
     &BRCH(4)+12),0,0,0, 60.0,60.0,0.0,230.0,0.0,0.0,100.0,230.0,230.0, &
     &1.0,80.0,2.0,1.0,1.0,0.1, 1.0,80.0,1.0,0.1)

! 1:[fixed_load] Fixed Load 
      CALL LOAD1P1_CFG(132.790562,60.0,60.0,10.0,2.0,2.0,0.0,0.0)

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_8(3), Bus2(3), NT_10(3)
      INTEGER  Bus1(3), Bus5(3), Bus4(3), Bus3(3)

! Control Signals

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(5), IBRCH(5), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 56

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 5

      DO IT_0 = 1,5
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 12

      IBRCH(2)     = NBRCH(SS(2))
      NBRCH(SS(2)) = NBRCH(SS(2)) + 15

      IBRCH(3)     = NBRCH(SS(3))
      NBRCH(SS(3)) = NBRCH(SS(3)) + 15

      IBRCH(4)     = NBRCH(SS(4))
      NBRCH(SS(4)) = NBRCH(SS(4)) + 18

      IBRCH(5)     = NBRCH(SS(5))
      NBRCH(SS(5)) = NBRCH(SS(5)) + 9
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_8(IT_0) = NODE(INODE + 21 + IT_0)
         Bus2(IT_0) = NODE(INODE + 24 + IT_0)
         NT_10(IT_0) = NODE(INODE + 30 + IT_0)
         Bus1(IT_0) = NODE(INODE + 33 + IT_0)
         Bus5(IT_0) = NODE(INODE + 36 + IT_0)
         Bus4(IT_0) = NODE(INODE + 42 + IT_0)
         Bus3(IT_0) = NODE(INODE + 48 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = 60.0

! 40:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = 60.0

! 60:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = 60.0

! 80:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = 60.0

! 120:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 130:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 150:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 170:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = 60.0

! 190:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 240:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

! 260:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = 60.0

! 270:[fft] On-Line Frequency Scanner 

! 290:[fft] On-Line Frequency Scanner 

! 310:[fft] On-Line Frequency Scanner 

! 320:[fft] On-Line Frequency Scanner 

! 330:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 4
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = 60.0

! 340:[fft] On-Line Frequency Scanner 

! 350:[pgb] Output Channel 'P2_5'

! 360:[pgb] Output Channel 'P1_2'

! 370:[pgb] Output Channel 'P3_4'

! 380:[pgb] Output Channel 'Q2_5'

! 390:[pgb] Output Channel 'Q1_2'

! 400:[pgb] Output Channel 'Q3_4'

! 410:[pgb] Output Channel 'P1_3'

! 420:[pgb] Output Channel 'P2_3'

! 430:[pgb] Output Channel 'P2_4'

! 440:[pgb] Output Channel 'Q1_3'

! 450:[pgb] Output Channel 'Q2_3'

! 460:[pgb] Output Channel 'Q2_4'

! 470:[pgb] Output Channel 'P4'

! 480:[pgb] Output Channel 'Q4'

! 490:[pgb] Output Channel 'P5'

! 500:[pgb] Output Channel 'Q5'

! 540:[datatap] Scalar/Array Tap 

! 550:[datatap] Scalar/Array Tap 

! 560:[datatap] Scalar/Array Tap 

! 570:[datatap] Scalar/Array Tap 

! 580:[datatap] Scalar/Array Tap 

! 590:[datatap] Scalar/Array Tap 

! 600:[datatap] Scalar/Array Tap 

! 610:[datatap] Scalar/Array Tap 

! 620:[datatap] Scalar/Array Tap 

! 630:[datatap] Scalar/Array Tap 

! 650:[pgb] Output Channel 'Vph5_rms'

! 660:[pgb] Output Channel 'Vf5_rms'

! 670:[pgb] Output Channel 'Vph4_rms'

! 680:[pgb] Output Channel 'Vf4_rms'

! 690:[pgb] Output Channel 'Vph3_rms'

! 700:[pgb] Output Channel 'Vf3_rms'

! 710:[pgb] Output Channel 'Vph2_rms'

! 720:[pgb] Output Channel 'Vf2_rms'

! 730:[pgb] Output Channel 'Vph1_rms'

! 740:[pgb] Output Channel 'Vf1_rms'

      RETURN
      END

